Repository gray-adeyi/orderlie-fe-react, pull requests merged in 2023-10, with the labels that each got.

#4 Created Vitejs and tailwind setup for Orderlie
  orderlie-fe-react/.eslintrc.cjs
  orderlie-fe-react/.gitignore
  orderlie-fe-react/README.md
  orderlie-fe-react/index.html
  orderlie-fe-react/package.json
  orderlie-fe-react/postcss.config.js
  orderlie-fe-react/public/vite.svg
  orderlie-fe-react/src/App.css
  orderlie-fe-react/src/App.jsx
  orderlie-fe-react/src/assets/react.svg
  orderlie-fe-react/src/index.css
  orderlie-fe-react/src/main.jsx
  orderlie-fe-react/tailwind.config.js
  orderlie-fe-react/vite.config.js
  orderlie-fe-react/yarn.lock
Labels: hacktoberfest-accepted

#6 Updated the readme.md file
  README.md
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#8 Expose dir
  README.md
  index.html
  orderlie-fe-react/.eslintrc.cjs
  orderlie-fe-react/.gitignore
  orderlie-fe-react/README.md
  package.json
  postcss.config.js
  public/vite.svg
  src/App.css
  src/App.jsx
  src/assets/react.svg
  src/index.css
  src/main.jsx
  tailwind.config.js
  vite.config.js
  yarn.lock
Labels: hacktoberfest, hacktoberfest-accepted

#10 Created a LICENSE.md file
  LICENSE.md
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#19 Added figma link for orderlie landing page ( Desktop Screen)
  README.md
Labels: hacktoberfest-accepted

#17 Created the Footer section of the home page and make it responsive
  src/App.jsx
  src/component/Footer.jsx
  src/main.jsx
  yarn.lock
Labels: hacktoberfest, hacktoberfest-accepted

#36 Added the Figma Link for Edit User Info Screen(Desktop)
  README.md
Labels: hacktoberfest-accepted

#37 Mobile edit user info screen
  README.md
Labels: hacktoberfest-accepted

#38 added figma link for the class list (desktop Screen)
  README.md
Labels: hacktoberfest-accepted

#40 Created second page and routing
  package-lock.json
  package.json
  src/App.css
  src/App.jsx
  src/assets/hom-img.png
  src/assets/image 3.png
  src/assets/image 4.png
  src/assets/image 5.png
  src/component/Footer.jsx
  src/component/Header.jsx
  src/component/Homepage/Overview.jsx
  src/component/offer/OfferItem.jsx
  src/component/offer/WhatWeOffer.jsx
  src/index.css
  src/main.jsx
  src/pages/Home/Homepage.jsx
  tailwind.config.js
  yarn.lock
Labels: hacktoberfest-accepted

#39 added update bio data figma link for desktop screen
  README.md
Labels: hacktoberfest-accepted

#41 Added Figma Link for Class List Page Screen (Mobile)
  README.md
Labels: hacktoberfest-accepted

#50 completed the new class page
  src/component/Homepage/Overview.jsx
  src/main.jsx
  src/pages/Home/NewClass.jsx
  yarn.lock
Labels: hacktoberfest-accepted, Frontend

#49 added figma link for the landing page (Mobile Screen)
  README.md
Labels: hacktoberfest-accepted, design

#52 solved issue #43
  src/App.jsx
  src/assets/Arrow 1.png
  src/assets/Arrow 1.svg
  src/assets/Aven.png
  src/assets/Frame 6.png
  src/assets/Oculus.png
  src/component/Footer.jsx
  src/component/offer/whatWeOffer.css
  src/index.css
  src/main.jsx
  src/pages/Home/Home.jsx
  src/pages/Home/Homepage.jsx
  src/pages/Home/editProfile.jsx
  src/pages/Home/landingPage.css
  src/pages/Home/landingPage.jsx
  tailwind.config.js
  yarn.lock
Labels: hacktoberfest, hacktoberfest-accepted, Frontend

#53 solved issue #44
  src/App.jsx
  src/assets/Group (1).png
  src/main.jsx
  src/pages/Home/NewClass.jsx
  src/pages/Home/editProfile.css
  src/pages/Home/editProfile.jsx
  src/pages/Home/landingPage.jsx
  tailwind.config.js
Labels: hacktoberfest-accepted, Frontend

#56 Worked on the Class List on the design page
  package.json
  src/component/Homepage/Overview.jsx
  src/main.jsx
  src/pages/Home/ClassList.jsx
  src/pages/Home/NewClass.jsx
  vite.config.js
  yarn.lock
Labels: hacktoberfest, hacktoberfest-accepted, Frontend

#58 Created Upload Biodata page
  package-lock.json
  src/component/Homepage/Overview.jsx
  src/index.css
  src/main.jsx
  src/pages/Home/ClassList.jsx
  src/pages/Home/NewClass.jsx
  src/pages/Home/UploadBioData.jsx
  yarn.lock
Labels: hacktoberfest, hacktoberfest-accepted, Frontend

#60 Worked On The api base integration
  package-lock.json
  package.json
  src/api/baseUrl.js
  yarn.lock
Labels: enhancement, help wanted, good first issue, hacktoberfest, hacktoberfest-accepted, Frontend, api integration

#75 Updated the color
  src/component/offer/whatWeOffer.css
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, design, Frontend

#76 updated the color
  src/component/offer/whatWeOffer.css
Labels: hacktoberfest, hacktoberfest-accepted
